---
title: Timur Safin - Making No Sense
repository: tsafin/tsafin.github.io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Try to be public. Again
logo: tsafin_twitter_small_logo.jpg
teaser: 400x250.gif
locale: en
url: 
feed:
  path: atom.xml
sass:
  load_paths:
    - _sass
    - _compass
  style: compressed
permalink: "/:categories/:title/"
kramdown:
  toc_levels: 1..2
highlighter: rouge
google_analytics_key: UA-84704404-1
gems:
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-compass
- jekyll-assets
owner:
  name: Timur Safin
  email: timur.safin@gmail.com
  facebook: timur.safin
  instagram: tsafin
  twitter: tsafin
  github: tsafin
  googleplus: "+TimurSafin1"
  linkedin: timursafin
  intersystems: 33801
  google:
    ad-client: 
    ad-slot: 
  bio: 
  photo: timur-safin-demo.png
  avatar: tsafin_twitter_small_logo.jpg
  disqus-shortname: tsafin-net
include:
- ".htaccess"
exclude:
- "*.less"
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- config
- gulpfile.js
- lib
- log
- node_modules
- package.json
- spec
- tmp
