---
title: Timur Safin - Making No Sense
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Try to be public. Again
logo: tsafin_twitter_small_logo.jpg
teaser: 400x250.gif
locale: en
url: 
feed:
  path: atom.xml
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
kramdown:
  toc_levels: 1..2
highlighter: rouge
google_analytics_key: UA-84704404-1
gems:
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
owner:
  name: Timur Safin
  email: timur.safin@gmail.com
  twitter: tsafin
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: tsafin_twitter_small_logo.jpg
  disqus-shortname: tsafin-net
include:
- ".htaccess"
exclude:
- "*.less"
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- config
- gulpfile.js
- lib
- log
- node_modules
- package.json
- spec
- tmp
